[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
]

runner = [
    "qemu-system-riscv64",
    "-machine", "virt",
    "-nographic",
    "-smp", "1",
    "-bios", "none",
    "-kernel", 
    # Cargo 会自动在这里追加内核文件路径
]
# 添加或修改这个 [alias] 段
[alias]
# 为 `build --release` 创建一个快捷方式 `b`
b = "build --release"

# 为 `run --release` 创建一个快捷方式 `r`
r = "run --release"
[profile.release]
debug = true # 强制在 release 版本中也加入完整的调试符号
